### ISSUE TITLE
Exception is thrown on an empty options list

### ISSUE THREAD

**Issue by alexanderadam** [AmyShackles/react-autosuggestions#15]
Thank you so much for `react-autosuggestions`! 🙌 

**Describe the bug**

Typing into the autosuggest input will raise an exception if the list of options is empty.

**To Reproduce**

```javascript
<AutoSuggest
  name="foo"
  options={[]}
  value={value}
  handleChange={onChange}
  styles={autoSuggestStyles}
/>
```

1. trying to type something 

**Expected behaviour**

no exception

**Additional context**

The error is `Uncaught TypeError: Cannot read properties of undefined (reading 'length')`

**Comment by AmyShackles** [comment]
@alexanderadam Good catch!  Thanks to @federico-paolillo, there's a fix in master.  I want to add some test cleanup and then I'll put out a new release.  Thank you both!
