### ISSUE TITLE
Issue with input and label ids taken from name param

### ISSUE THREAD

**Issue by mTpChris** [AmyShackles/react-autosuggestions#17]
**Is your feature request related to a problem? Please describe.**
I have to render the same autosuggest form for responsive design. One is hidden in mobile viewport and the other in computer viewport.  The result is that I have two inputs with the same id witch is not suitable.

**Describe the solution you'd like**
It would be nice to have an 'id' props and maybe a 'class' props.

**Describe alternatives you've considered**
I have none.

**Additional context**
The input id is built from name props.

Thank you.

**Comment by AmyShackles** [comment]
@mTpChris Released a new minor version that allows you to optionally specify an id to use as the basis for generating the ids of nested elements rather than having them be based off the name.  Let me know if that doesn’t solve your issue and I can reopen the ticket.

**Comment by mTpChris** [comment]
Thank you so much @AmyShackles for your reactivity ! This will solve my issue for sure.
