### ISSUE TITLE
CSS overwriting

### ISSUE THREAD

**Issue by mTpChris** [AmyShackles/react-autosuggestions#19]
Hello,

**Is your feature request related to a problem? Please describe.**
All `li` tags' styles are overwrited by styles in index.css (li:hover, li.highlighted and input.loading) on the entire page.

**Describe the solution you'd like**
Make those styles optionnal or remove them so we can apply our own styles on this specific component.

**Describe alternatives you've considered**
Overriding these styles in my app but it's not optimal at all.

**Additional context**
None.

Thank you for your work !

**Comment by AmyShackles** [comment]
If you have your own css file, you should be able to write rules [that target the same specificity](https://github.com/AmyShackles/react-autosuggestions#css-styling-not-configurable-by-style-object-in-case-you-want-to-override) and your CSS should overwrite what’s already set.

Please let me know if this is not the case and provide an example and I’ll look into it when I have a chance.

**Comment by mTpChris** [comment]
Hello @AmyShackles , thank you for your response.

I don't have any css file because I'm using NextJs with TailwindCSS and DaisyUI. Also I'm not a big fan of overriding rules again and again, production packages will be bigger and you can have a visual stuterings (in all the page in this case) before all CSS finish loading all stylesheets. That's why I'm using TailwindCSS and DaisyUI. Moreover the li:hover rule does not only target your component, witch is not very optimized.

Thank you again.

**Comment by AmyShackles** [comment]
@mTpChris Removed the hardcoded rules and refactored the code to set those styles through the styles object with the previously hardcoded values as the default options.

Please let me know if that doesn't resolve the issue for you and I'll be happy to reopen the issue.

**Comment by mTpChris** [comment]
Thank you so much @AmyShackles, now it's perfect, you rock !
